# uv run python -m train --config-name=gpu_4090_0.8b ++paths.model_name=qwen08b_001
defaults:
  - base
  - _self_

model:
  model_name_or_path: "Qwen/Qwen3.5-0.8B"
  quantize_int4: true
  max_new_tokens: 256

grpo:
  group_size: 8
  learning_rate: 3.e-5
  max_steps: 5000
  log_interval: 10
  checkpoint_interval: 200
