# Sim training with Qwen3.5-9B on A100
# uv run python -m train --config-name=gpu_a100_8b ++paths.model_name=qwen9b_001
defaults:
  - sim_base
  - _self_

model:
  model_name_or_path: "Qwen/Qwen3.5-9B"

grpo:
  lr_max: 5.e-6
  log_interval: 10
  checkpoint_interval: 200
