# Sim training with Qwen3.5-2B
# uv run python -m train --config-name=gpu_4090_2b ++paths.model_name=qwen2b_001
defaults:
  - sim_base
  - _self_

model:
  model_name_or_path: "Qwen/Qwen3.5-2B"
  quantize_int4: true

grpo:
  log_interval: 10
  checkpoint_interval: 200
