# Sim training with Qwen3.5-4B
# uv run python -m train --config-name=gpu_4090 ++paths.model_name=qwen4b_001
defaults:
  - sim_base
  - _self_

model:
  model_name_or_path: "Qwen/Qwen3.5-4B"

grpo:
  log_interval: 10
  checkpoint_interval: 200
